project:
  type: website

website:
  title: "Closeread"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: guide/index.qmd
        text: Guide
      - href: demos/index.qmd
        text: Demos
      - href: reference/index.qmd
        text: Reference

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



