# workflow to build docs site and publish to github pages

on:
  workflow_dispatch:
  pull_request:
    branches: main

name: closeread-publish-test-site

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest
    container:
      image: ucbscf/berkeley-stat-course:latest
      options: --user root
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout closeread repo
        uses: actions/checkout@v4

      - name: Extension into docs site
        run: |
          # copy closeread extension into docs 
          cd docs
          mkdir -p _extensions/
          cp -Rf ../_extensions/closeread _extensions/
        shell: bash
            
      - name: Render and Publish 
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          path: docs
          
